input {
  # Standalone LFV tests don't require inputs
  # You need to configure your desired inputs e.g.
  #
  # kinesis {
  #   id                  => "one_input_kinesis_0"
  #   kinesis_stream_name => "foo-bar-stream"
  #   codec               => "cloudwatch_logs"
  # }
}

filter {
  if [service] == "foo" {
    mutate { add_field => { "pipeline" => "two" } }
  }

  if [service] == "bar" {
    mutate { add_field => { "pipeline" => "three" } }
  }

  mutate { remove_field => ["event", "host"] }
}

output {
  stdout { codec => json_lines }
}
