ARG USER=user

FROM ${USER}/logstash-p2p:latest

USER root

RUN microdnf install -y diffutils wget && microdnf clean all

RUN wget --progress=dot:giga https://github.com/magnusbaeck/logstash-filter-verifier/releases/download/v2.0.0-beta.3/logstash-filter-verifier_v2.0.0-beta.3_linux_amd64.tar.gz && \
  tar xzf logstash-filter-verifier_v2.0.0-beta.3_linux_amd64.tar.gz -C /usr/bin && \
  rm logstash-filter-verifier_v2.0.0-beta.3_linux_amd64.tar.gz

USER logstash

COPY --chown=logstash:root --chmod=755 test.sh /usr/share/logstash/test.sh
COPY --chown=logstash:root --chmod=755 testcases /usr/share/logstash/tests
