input {
  # The stdin input is used for testing
  # You need to configure your desired inputs e.g.
  #
  # kinesis {
  #   id                  => "one_input_kinesis_0"
  #   kinesis_stream_name => "foo-bar-stream"
  #   codec               => "cloudwatch_logs"
  # }

  stdin {
    id    => "one_input_stdin_0"
    codec => json
  }
}

filter {
  mutate {
    id           => "one_filter_mutate_1"
    remove_field => ["event", "host"]
  }
}

output {
  stdout { id => "one_output_stdout_0" }

  if [service] == "foo" {
    pipeline {
      id      => "one_output_pipeline_0"
      send_to => two
    }
  }

  if [service] == "bar" {
    pipeline {
      id      => "one_output_pipeline_1"
      send_to => three
    }
  }
}
