input {
  pipeline {
    id      => "three_input_pipeline_0"
    address => three
  }
}

filter {
  mutate {
    id        => "three_filter_mutate_0"
    add_field => { "pipeline" => "three" }
  }
}

output {
  stdout { id => "three_output_stdout_0" }
}
