input {
  pipeline {
    id      => "two_input_pipeline_0"
    address => two
  }
}

filter {
  mutate {
    id        => "two_filter_mutate_0"
    add_field => { "pipeline" => "two" }
  }
}

output {
  stdout { id => "two_output_stdout_0" }
}
